name: kdocker
confinement: classic
grade: devel
base: core24
adopt-info: kdocker
compression: lzo
apps:
    kdocker:
        common-id: com.kdocker.KDocker
        desktop: usr/share/applications/com.kdocker.KDocker.desktop
        command: usr/bin/kdocker
        plugs:
        - home
        - x11
        - desktop
        environment:
          QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/qt6/plugins/platforms
slots:
    session-dbus-interface:
        interface: dbus
        name: com.kdocker.KDocker
        bus: session
parts:
    kdocker:
        parse-info:
        - usr/share/metainfo/com.kdocker.KDocker.metainfo.xml
        plugin: cmake
        cmake-generator: Ninja
        source: .
        source-type: local
        cmake-parameters:
        - -DCMAKE_INSTALL_PREFIX=/usr
        - -DCMAKE_BUILD_TYPE=RelWithDebInfo
        build-packages:
        - qt6-base-dev
        - libx11-dev
        - libxcb1-dev
        stage-packages:
        - libx11-6
        - libxcb1
        - libqt6core6
        - libqt6dbus6
        - libqt6gui6
        - libqt6widgets6
