name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install deps
      run: |
        sudo apt-get install -y qt6-base-dev libxcb1-dev libx11-xcb-dev libxmu-dev libxpm-dev build-essential
    - name: Build
      run: |
        qmake6
        make
