name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install deps
      run: |
        sudo apt-get install -y build-essential cmake ninja-build qt6-base-dev libx11-dev libxcb1-dev libxmu-dev
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -G Ninja ..
        ninja

  build-snap:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Snap
      uses: snapcore/action-build@v1
      id: snapcraft
    - name: Upload snap artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.snapcraft.outputs.snap }}
        path: ${{ steps.snapcraft.outputs.snap }}
