name: Flatpak

on: push

jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-6.7
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: kdocker.flatpak
        manifest-path: resources/flatpak/com.kdocker.KDocker.yml
        cache-key: flatpak-builder-${{ github.sha }}
