name: Package

on:
  push:
    tags:
      - '*'

jobs:
  Snap:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup snapcraft.yaml
      run: |
        ln -s resources/snap/snapcraft.yaml snapcraft.yaml
    - name: Snap
      uses: snapcore/action-build@v1
      id: snapcraft
    - name: Upload snap artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.snapcraft.outputs.snap }}
        path: ${{ steps.snapcraft.outputs.snap }}

  Flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-6.7
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      if: ${{ matrix.arch != 'x86_64' }}
      run: |
        dnf -y install docker
    - name: Set up QEMU
      if: ${{ matrix.arch != 'x86_64' }}
      id: qemu
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: kdocker.flatpak
        manifest-path: resources/flatpak/com.kdocker.KDocker.yml
        cache-key: flatpak-builder-${{ github.sha }}
        arch: ${{ matrix.arch }}

